# Generated by Django 4.1.7 on 2023-06-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='size',
        ),
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.ManyToManyField(related_name='shoes', to='ShoesStoreApp.shoessize'),
        ),
    ]
