# Generated by Django 4.1.7 on 2023-06-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesStoreApp', '0002_shoessize_remove_shoes_size_shoes_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoessize',
            old_name='name',
            new_name='size',
        ),
    ]
