# Generated by Django 4.2.2 on 2023-06-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesStoreApp', '0003_rename_name_shoessize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='type',
            field=models.CharField(choices=[('Running shoes', 'Running shoes'), ('Basketball shoes', 'Basketball shoes'), ('Tennis shoes', 'Tennis shoes'), ('Football shoes', 'Football shoes'), ('Sneakers', 'Sneakers'), ('Sandals', 'Sandals')], max_length=255),
        ),
    ]
