# Generated by Django 4.2.2 on 2023-06-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesStoreApp', '0004_alter_shoes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
