# Generated by Django 4.2.2 on 2023-07-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoesStoreApp', '0005_orderitem_selected_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
